# Generated by Django 4.0.6 on 2022-09-15 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='film',
            fields=[
                ('film_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('film_name', models.CharField(max_length=100)),
                ('cover_url', models.CharField(max_length=500)),
                ('release_date', models.CharField(max_length=50)),
                ('film_story', models.CharField(max_length=2000)),
                ('film_genre', models.CharField(max_length=50)),
                ('film_censor', models.CharField(max_length=50)),
                ('film_duration', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('film_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('stopped', 'Stopped')], default='active', max_length=30)),
                ('cast_n_crew', models.CharField(max_length=1000)),
                ('tn_code', models.CharField(default='NA', max_length=50)),
                ('ptm_code', models.CharField(default='NA', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='track',
            fields=[
                ('track_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('track_location', models.CharField(max_length=50)),
                ('is_currently_tracking', models.CharField(default='Y', max_length=50)),
                ('loc_real_name', models.CharField(max_length=50)),
                ('theatre_code', models.CharField(default='null', max_length=30)),
                ('source', models.CharField(default='bms', max_length=30)),
                ('offset', models.CharField(default='na', max_length=40)),
                ('offset_check', models.CharField(default='na', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('film', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.film')),
                ('is_tracking', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='show',
            fields=[
                ('show_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('show_time', models.CharField(max_length=50)),
                ('screen_name', models.CharField(blank=True, max_length=50)),
                ('show_date', models.CharField(max_length=50)),
                ('theatre_code', models.CharField(max_length=50)),
                ('last_modified', models.CharField(default='na', max_length=50)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.film')),
            ],
        ),
        migrations.CreateModel(
            name='mdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('show_date', models.CharField(max_length=50)),
                ('show_count', models.IntegerField(default=0)),
                ('category_name', models.CharField(blank=True, max_length=50)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('booked_seats', models.CharField(default='0', max_length=50)),
                ('available_seats', models.CharField(default='0', max_length=50)),
                ('total_seats', models.CharField(default='0', max_length=50)),
                ('theatre_code', models.CharField(max_length=50)),
                ('theatre_location', models.CharField(max_length=50)),
                ('theatre_name', models.CharField(default='Not Available', max_length=500)),
                ('last_modified', models.CharField(max_length=50)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.film')),
            ],
        ),
    ]
