# Generated by Django 4.0.1 on 2022-01-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='film_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=100)),
                ('film_id', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=50)),
                ('film_loc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='film_loc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_location', models.CharField(max_length=100)),
                ('venue_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ft_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=100)),
                ('film_id', models.CharField(max_length=100)),
                ('theatre_id', models.CharField(max_length=100)),
                ('show_id', models.CharField(max_length=100)),
                ('available_seat', models.IntegerField()),
                ('total_seat', models.IntegerField()),
                ('booked_seat', models.IntegerField()),
                ('Show_time', models.CharField(max_length=100)),
                ('show_date', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=30)),
                ('last_modified', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('show_id', 'film_name'),
            },
        ),
    ]
