# Generated by Django 4.0.1 on 2022-01-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ft_data',
            options={'ordering': ('show_date', 'film_name')},
        ),
        migrations.AddField(
            model_name='ft_data',
            name='film_loc',
            field=models.CharField(default='not set', max_length=50),
        ),
    ]
