# Generated by Django 4.0.6 on 2022-08-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='ptm_code',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='track',
            name='offset',
            field=models.CharField(default='na', max_length=40),
        ),
        migrations.AddField(
            model_name='track',
            name='offset_check',
            field=models.CharField(default='na', max_length=40),
        ),
        migrations.AddField(
            model_name='track',
            name='source',
            field=models.CharField(default='bms', max_length=30),
        ),
    ]
