# Generated by Django 4.0.1 on 2022-01-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ft_data_options_film_det_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film_det',
            name='image_url',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
