# Generated by Django 4.0.1 on 2022-01-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_film_det_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film_det',
            name='image_url',
            field=models.CharField(default='none', max_length=150),
        ),
    ]
