# Generated by Django 4.0.6 on 2022-09-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_track_offset_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
