# Generated by Django 4.0.1 on 2022-01-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_film_det_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film_det',
            name='image_url',
            field=models.CharField(default='18am-padi-et00105977-28-06-2019-01-18-50', max_length=150),
        ),
    ]
