# Generated by Django 4.0.1 on 2022-01-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_film_det_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='film_det',
            name='film_real_name',
            field=models.CharField(default='Not Set', max_length=100),
        ),
    ]
