# Generated by Django 4.0.6 on 2022-09-29 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_film_highlight_film_language_film_other_lang_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='highlight',
        ),
        migrations.RemoveField(
            model_name='film',
            name='language',
        ),
        migrations.RemoveField(
            model_name='film',
            name='other_lang_code',
        ),
    ]
