# Generated by Django 4.0.1 on 2022-01-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_film_det_film_real_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ft_data',
            name='category_name',
            field=models.CharField(default='Normal', max_length=50),
        ),
        migrations.AddField(
            model_name='ft_data',
            name='screen_name',
            field=models.CharField(default='Not set', max_length=50),
        ),
    ]
