# Generated by Django 4.0.1 on 2022-01-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_film_det_film_censor_film_det_film_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film_det',
            name='film_story',
            field=models.CharField(default='Not Available', max_length=500),
        ),
    ]
